# Generated by Django 3.2.16 on 2024-01-05 14:05

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('name', models.CharField(max_length=255, verbose_name='Username')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10, verbose_name='Gender')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email address')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=15, region=None, unique=True, verbose_name='Mobile Number')),
                ('instagram', models.CharField(max_length=255, unique=True, verbose_name='Instagram')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('category', models.CharField(choices=[('rapper', 'Rapper'), ('skater', 'Skater'), ('graphic_designer', 'Graphic Designer')], max_length=20, verbose_name='Category')),
                ('experience', models.IntegerField(verbose_name='Experience')),
                ('unique_code', models.CharField(editable=False, max_length=100, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
