# Generated by Django 4.2.9 on 2024-02-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notification",
            field=models.BooleanField(default=False),
        ),
    ]
