# Generated by Django 4.1.3 on 2024-01-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_categoryname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoryname",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
