# Generated by Django 4.2.9 on 2024-02-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_categoryname_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notification_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Notification Enabled"
            ),
        ),
    ]
